name: CI
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 12 * * 1'

jobs:    
  build:
    runs-on: 
      - ubuntu-latest
      - macos-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 28.1
          - snapshot
        ignore_warnings:
          - true
        check:
          - load-file
          - byte-compile
          - checkdoc
          - package-lint
    steps:
    - uses: actions/checkout@v3
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: leotaku/elisp-check@v1.3
      with:
        file: init.el
        check: ${{ matrix.check }}
        ignore_warnings: ${{ matrix.ignore_warnings }}
